import React from 'react';
import './Menu.css'

class Menu extends React.Component {
    render() {
      return (
      <div className="Menu">
          <div className="MenuHeader">Boaty McBoatface</div>
          <div className="MenuSubHeader">Dashboard</div>
        {this.props.children}
        <div className="MenuFooter">
          <p>
            Font generated by <a href="https://www.flaticon.com"> flaticon.com</a>.
            Under 
            <a href="http://creativecommons.org/licenses/by/3.0/"> CC-BY</a>: 
            <a data-file="003-car" href="https://www.flaticon.com/authors/smashicons"> Smashicons</a>, 
            <a data-file="004-boat" href="https://www.flaticon.com/authors/kiranshastry"> Kiranshastry</a>, 
            <a data-file="001-group" href="https://www.flaticon.com/authors/prosymbols"> Prosymbols</a>, 
            <a data-file="002-crate" href="https://www.flaticon.com/authors/srip"> srip</a>
          </p>
        </div>
      </div>
      );
    }
}

export default Menu;