version: '3.9'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  backend:
    build: ./
    links:
      - db
    ports:
      - "9000:9000"
    environment:
      PORT: 9000
